"""Build JSON datasets for the Efectividad Mecanicos web app from the Excel sources.

Reads the Exceles from app/excel/ (committed to the repo) and writes JSON to
app/data/ (regenerated by the GitHub Action on every push that touches those
Excels).

Outputs:
  - app/data/tareas.json     : detail rows from 'Efectividad Mecanicos.xlsx'
                                (sheets: Enero, Hoja1, Hoja6, Hoja2, Hoja5, ...)
  - app/data/ordenes.json    : {DocNum -> Tipo de orden} from
                                'Listado de Ordenes de Mantenimiento.xlsx'
  - app/data/metricas.json   : {yyyy-mm -> {codigoEmpleado -> metrics}}, with the
                               special key '__total__' for the per-month total
                               row. Replicates all DAX measures from the PBI
                               model (Hs Totales, Hs Mecanico, Margen
                               Productividad, % Procutivo, Supera 80Hs,
                               Supera %50).

Usage:
    python app/build_data.py
"""
import datetime
import json
from collections import defaultdict
from pathlib import Path

import openpyxl

APP_DIR = Path(__file__).resolve().parent
EXCEL_DIR = APP_DIR / "excel"
OUT = APP_DIR / "data"
TAREAS_XLSX = EXCEL_DIR / "efectividad.xlsx"
ORDENES_XLSX = EXCEL_DIR / "ordenes.xlsx"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _to_minutes(v):
    """Coerce Excel cell to a number of minutes. Excel sometimes stores durations as time/datetime."""
    if v is None:
        return 0.0
    if isinstance(v, (int, float)):
        return float(v)
    if isinstance(v, datetime.time):
        return v.hour * 60 + v.minute + v.second / 60.0
    if isinstance(v, datetime.timedelta):
        return v.total_seconds() / 60.0
    if isinstance(v, datetime.datetime):
        return (v - datetime.datetime(1899, 12, 30)).total_seconds() / 60.0
    if isinstance(v, str):
        s = v.strip().replace(",", ".")
        try:
            return float(s)
        except ValueError:
            return 0.0
    return 0.0


def _to_date(v):
    if isinstance(v, datetime.datetime):
        return v.date().isoformat()
    if isinstance(v, datetime.date):
        return v.isoformat()
    if isinstance(v, str):
        s = v.strip()
        for fmt in ("%d/%m/%Y", "%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
            try:
                return datetime.datetime.strptime(s.split()[0], fmt).date().isoformat()
            except ValueError:
                pass
    return None


# ---------------------------------------------------------------------------
# Data loaders
# ---------------------------------------------------------------------------
def load_tareas():
    """Read task rows from every relevant sheet of 'efectividad.xlsx'."""
    wb = openpyxl.load_workbook(str(TAREAS_XLSX), data_only=True)
    rows_out = []
    # Sheets to scan, in chronological order:
    sheet_names = [
        "Enero", "Hoja1", "Hoja6", "Hoja2", "Hoja5",
        "Hoja1 (tdu enero y diciembre)", "Hoja3",
    ]
    for sheet_name in sheet_names:
        if sheet_name not in wb.sheetnames:
            continue
        ws = wb[sheet_name]
        headers = [c.value for c in ws[1]]
        idx = {h: i for i, h in enumerate(headers) if h}
        doc_col = idx.get("DocNum")
        emp_cod = idx.get("Codigo empleado")
        emp_nom = idx.get("Empleado") or idx.get("Nombre empleado")
        fecha_col = idx.get("Fecha inicio")
        trab_col = idx.get("Horas Trabajadas (minutos)") or idx.get("Horas trabajadas")
        std_col = idx.get("TiempoEstandarPorMecanico")
        dif_col = idx.get("Dif HTrabajadas vs TExMecanico")
        tarea_col = idx.get("Tarea")
        tarea_cod_col = idx.get("Codigo tarea")
        if fecha_col is None:
            continue

        sheet_rows = 0
        for r in ws.iter_rows(min_row=2, values_only=True):
            if not r or all(v is None for v in r):
                continue
            fecha = _to_date(r[fecha_col])
            if fecha is None:
                continue
            rows_out.append({
                "docNum": r[doc_col] if doc_col is not None else None,
                "empleadoCodigo": str(r[emp_cod]) if emp_cod is not None and r[emp_cod] is not None else None,
                "empleadoNombre": r[emp_nom] if emp_nom is not None else None,
                "fecha": fecha,
                "horasTrabajadasMin": _to_minutes(r[trab_col]) if trab_col is not None else 0.0,
                "tiempoEstandarMin": _to_minutes(r[std_col]) if std_col is not None else 0.0,
                "difMin": _to_minutes(r[dif_col]) if dif_col is not None else 0.0,
                "tarea": r[tarea_col] if tarea_col is not None else None,
                "codigoTarea": r[tarea_cod_col] if tarea_cod_col is not None else None,
            })
            sheet_rows += 1
        print(f"  [sheet] {sheet_name}: {sheet_rows:,} filas")
    return rows_out


def load_ordenes():
    """Read 'ordenes.xlsx' and return a {DocNum -> Tipo} map."""
    wb = openpyxl.load_workbook(str(ORDENES_XLSX), data_only=True)
    ws = wb["Hoja1"]
    out = {}
    for r in ws.iter_rows(min_row=2, values_only=True):
        if not r or r[0] is None:
            continue
        try:
            out[str(int(r[0]))] = r[1]
        except (TypeError, ValueError):
            continue
    return out


# ---------------------------------------------------------------------------
# DAX replication
# ---------------------------------------------------------------------------
def compute_metrics(tareas):
    """Replicate the DAX measures from the PBI model (see README for formulas)."""
    # Distinct employees per (docNum, fecha, codigoTarea) for the "Repartido" measure
    key_employees = defaultdict(set)
    for r in tareas:
        key_employees[(str(r["docNum"]), r["fecha"], r["codigoTarea"])].add(r["empleadoCodigo"])

    # Per (docNum, fecha, codigoTarea, codigoEmpleado) -> MAX(std)
    seen_keys = {}
    for r in tareas:
        key = (str(r["docNum"]), r["fecha"], r["codigoTarea"], r["empleadoCodigo"])
        if r["tiempoEstandarMin"] > seen_keys.get(key, 0):
            seen_keys[key] = r["tiempoEstandarMin"]

    # Per (empleado, yyyy-mm): HsTot (repartido), HsMec, Positivos
    per = defaultdict(lambda: {"hsTot": 0.0, "trab": 0.0, "trab_pos": 0.0,
                               "std_pos": 0.0, "rows_total": 0, "rows_prod": 0})
    for (doc, fecha, tarea, emp), max_std in seen_keys.items():
        cant = len(key_employees[(doc, fecha, tarea)])
        if cant > 0:
            per[(emp, fecha[:7])]["hsTot"] += max_std / cant
    for r in tareas:
        k = (r["empleadoCodigo"], r["fecha"][:7])
        per[k]["trab"] += r["horasTrabajadasMin"]
        per[k]["rows_total"] += 1
        if r["difMin"] >= 0:
            per[k]["trab_pos"] += r["horasTrabajadasMin"]
            per[k]["std_pos"] += r["tiempoEstandarMin"]
            per[k]["rows_prod"] += 1

    out = defaultdict(dict)
    for (emp, ym), v in per.items():
        hsTot = v["hsTot"] / 60.0
        hsMec = v["trab"] / 60.0
        trab_pos = v["trab_pos"] / 60.0
        std_pos = v["std_pos"] / 60.0
        margen = (std_pos / trab_pos - 1) * 100 if trab_pos else 0
        pctProd = (v["rows_prod"] / v["rows_total"] * 100) if v["rows_total"] else 0
        out[ym][emp] = {
            "hsTot": round(hsTot, 4),
            "hsMec": round(hsMec, 4),
            "margen": round(margen, 4),
            "pctProd": round(pctProd, 4),
            "supera80": "SI" if hsTot >= 80 else "NO",
            "supera50": "SI" if pctProd >= 50 else "NO",
        }

    # Per-month totals (PBI's "Total" row recurses across all rows of that month)
    per_ym = defaultdict(lambda: {"hsTot": 0.0, "trab": 0.0, "trab_pos": 0.0,
                                 "std_pos": 0.0, "rows_total": 0, "rows_prod": 0})
    for (doc, fecha, tarea, emp), max_std in seen_keys.items():
        cant = len(key_employees[(doc, fecha, tarea)])
        if cant > 0:
            per_ym[fecha[:7]]["hsTot"] += max_std / cant
    for r in tareas:
        ym = r["fecha"][:7]
        per_ym[ym]["trab"] += r["horasTrabajadasMin"]
        per_ym[ym]["rows_total"] += 1
        if r["difMin"] >= 0:
            per_ym[ym]["trab_pos"] += r["horasTrabajadasMin"]
            per_ym[ym]["std_pos"] += r["tiempoEstandarMin"]
            per_ym[ym]["rows_prod"] += 1

    for ym, v in per_ym.items():
        hsTot = v["hsTot"] / 60.0
        hsMec = v["trab"] / 60.0
        trab_pos = v["trab_pos"] / 60.0
        std_pos = v["std_pos"] / 60.0
        margen = (std_pos / trab_pos - 1) * 100 if trab_pos else 0
        pctProd = (v["rows_prod"] / v["rows_total"] * 100) if v["rows_total"] else 0
        out[ym]["__total__"] = {
            "hsTot": round(hsTot, 4),
            "hsMec": round(hsMec, 4),
            "margen": round(margen, 4),
            "pctProd": round(pctProd, 4),
            "supera80": "SI" if hsTot >= 80 else "NO",
            "supera50": "SI" if pctProd >= 50 else "NO",
            "isTotal": True,
        }
    return dict(out)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    for p in (TAREAS_XLSX, ORDENES_XLSX):
        if not p.exists():
            raise SystemExit(f"Falta el Excel: {p}")

    OUT.mkdir(parents=True, exist_ok=True)

    print("Leyendo tareas...")
    tareas = load_tareas()
    print(f"  -> {len(tareas):,} filas totales")
    OUT.joinpath("tareas.json").write_text(
        json.dumps(tareas, ensure_ascii=False), encoding="utf-8")
    print(f"  -> escrito {OUT / 'tareas.json'}")

    print("Leyendo ordenes...")
    ordenes = load_ordenes()
    print(f"  -> {len(ordenes):,} ordenes")
    OUT.joinpath("ordenes.json").write_text(
        json.dumps(ordenes, ensure_ascii=False), encoding="utf-8")
    print(f"  -> escrito {OUT / 'ordenes.json'}")

    print("Calculando metricas (DAX)...")
    metricas = compute_metrics(tareas)
    total_pairs = sum(len(v) for v in metricas.values())
    print(f"  -> {total_pairs:,} (empleado, mes) pares")
    OUT.joinpath("metricas.json").write_text(
        json.dumps(metricas, ensure_ascii=False), encoding="utf-8")
    print(f"  -> escrito {OUT / 'metricas.json'}")

    print("Listo.")


if __name__ == "__main__":
    main()
